sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

install:
  - wget -qO- http://www.cmake.org/files/v3.1/cmake-3.1.0-Linux-x86_64.tar.gz | tar xvz

before_script:
  - mkdir build
  - cd build
  - ./cmake-3.1.0-Linux-x86_64/bin/cmake --version
  - ./cmake-3.1.0-Linux-x86_64/bin/cmake ../Tests -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
  - cd ..

script:
  - cd build
  - make
  - cd ..
  - ./build/Tests -p -t
